---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-service
  template:
    metadata:
      labels:
        app: crud-service
    spec:
      containers:
      - name: crud-service
        image: go-microservice:crud-service
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_HOST
          value: 192.168.0.130
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DB
        - name: LOADBALANCER_URL
          value: http://192.168.49.2/
---
apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: ClusterIP
  selector:
    app: crud-service
  ports:
  - port: 8081
    targetPort: 8081
