---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-service
  template:
    metadata:
      labels:
        app: crud-service
    spec:
      containers:
      - name: crud-service
        image: go-microservice:crud-service   # <- CHANGE THIS
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable
        envFrom:
        - secretRef:
            name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: ClusterIP
  selector:
    app: crud-service
  ports:
  - port: 8080
    targetPort: 8080
